### ISSUE TITLE
Cannot configure working_dir when starting the server

### ISSUE THREAD

**Issue by quangbuule** [sublimelsp/LSP-eslint#18]
Some of the eslint rules use `process.cwd()`, so not having configuration to change the working_dir is hard for the case having a sub-folder of the project in another workspace.

VSCode eslint extension has `eslint.workingDirectories` configuration which can be use as cwd when starting the lang server.

**Comment by rchl** [comment]
Added support for it in https://github.com/sublimelsp/LSP-eslint/pull/30

**Comment by rchl** [comment]
Released in [v1.1.0](https://github.com/sublimelsp/LSP-eslint/releases/tag/1.1.0)
