### ISSUE TITLE
Handle the eslint/noLibrary request

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-eslint#22]
I don't know what it is supposed to do:

```
:: <-- eslint eslint/noLibrary(3): {'source': {'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/out/eslintServer.js'}}
:: ~~> eslint 3: {'code': -32601, 'message': 'eslint/noLibrary'}
```

**Comment by rchl** [comment]
It looks like it's triggered when eslint dependency was not found in the project or globally to notify you that it can't work.

https://github.com/microsoft/vscode-eslint/blob/9b757bcee341adc983fdb9a95a4193b39a9ac34b/server/src/eslintServer.ts#L816-L819

In vscode a notification is shown telling user to install the dependency.
https://github.com/microsoft/vscode-eslint/blob/b3a3c5d61a99bbbc4c146bf59aee5a89ab21ff76/client/src/extension.ts#L1259

**Comment by rchl** [comment]
Fixed in https://github.com/sublimelsp/LSP-eslint/releases/tag/1.4.1
