### ISSUE TITLE
Cannot lint HTML file by default

### ISSUE THREAD

**Issue by lzaaldian** [sublimelsp/LSP-eslint#24]
Hello,

I'm having hard time to make eslint work on HTML files.

What I have done:

- Run `eslint --init` on root project directory
- Install `eslint-plugin-html`
- Activate HTML plugin

```
...
" plugins": [
  "html"
]
...
```

It works on Visual Studio Code, but I couldn't make it work on Sublime Text. Can anybody share how to properly enable linting HTML file?

**Comment by rchl** [comment]
For the `lsp-eslint` to initialize in HTML documents you need to enable it for that syntax. Use configuration like this other package:
https://github.com/sublimelsp/LSP-html/blob/256009b610c736cbf366d8ddb52a2c636f5dce31/LSP-html.sublime-settings#L3-L12
(minus the PHP).

**Comment by lzaaldian** [comment]
Thank you for your help!

Here's my settings for LSP-eslint to enable linting HTML files according to your suggestion.

<img width="1552" alt="Jepretan Layar 2020-05-31 pukul 8 11 43 AM" src="https://user-images.githubusercontent.com/3760093/83342196-838ec000-a316-11ea-8f7d-e757ca483591.png">
