### ISSUE TITLE
Handle the eslint/exitCalled notification

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-eslint#26]
When quick-switching projects, I get this unhandled notification from eslint:
```
:: <?  lsp-eslint eslint/exitCalled: [0, 'Error: stack\n    at process.exit (/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/out/eslintServer.js:190:17)\n    at /home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-languageserver/lib/main.js:1021:25\n    at handleNotification (/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:494:43)\n    at processMessageQueue (/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:271:17)\n    at Immediate._onImmediate (/home/raoul/.config/sublime-text-3/Cache/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:258:13)\n    at processImmediate (internal/timers.js:439:21)']
```

**Comment by rchl** [comment]
For reference, vscode extension handling:
https://github.com/microsoft/vscode-eslint/blob/1cad9da58888317a4a5fd5cbe6563f2446d6129f/client/src/extension.ts#L1230-L1234

I wonder if we should start thinking about having some generic notification popups.
I suppose we can only have per-view though.

**Comment by rchl** [comment]
I can only think of using the output panel for showing those kinds of messages.

I think that a dialog would be too intrusive.

Any better suggestions?

**Comment by rchl** [comment]
Well, this particular one is not that useful IMO so we can just do nothing but I'm thinking about generic solution.

**Comment by rwols** [comment]
I think handling it with `pass` is fine.

**Comment by rchl** [comment]
Fixed in https://github.com/sublimelsp/LSP-eslint/releases/tag/1.4.1.
