### ISSUE TITLE
No support for "probe" setting

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-eslint#36]
vscode-eslint has a `probe` setting:

```js
"eslint.probe": {
    "scope": "resource",
    "type": "array",
    "items": {
        "type": "string"
    },
    "default": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "html",
        "vue",
        "markdown"
    ],
    "description": "An array of language ids for which the extension should probe if support is installed."
},
```

- That setting is processed by the extension and not the server.
- The probe list is checked against the currently open document and based on that the extension decides whether the server will receive notifications about the file or not.
- Based on the result of the previous check, the `validate` option is set to either `on`, `off`, or `probe`
- If `validate` is set to `probe` then the server will:
  - not report errors related to failure to load the eslint library if that's the case
  - if eslint library is not missing then it will apply some default settings based on file extension so that even if there is no proper eslint configuration in the project, the basic validation will work
- Currently, we are hardcoding `validate` to `on` so eslint is unconditionally enabled for all files that match the list of our syntaxes/selectors.
- Eslint extension validates the document against the probe list during handling of:
  - `workspace/configuration`
  - `didOpen` hook
- The server will send a `eslint/probeFailed` message if probing has resulted with setting `validate` to `off` so that client can cache the result

**Comment by rchl** [comment]
To make this work we would need access to `languageId` from the `on_workspace_configuration` handler.

We also don't have the equivalent of `didOpen` hook so that we could decide whether we notify the server about the file or not. But we could live without that for now and just support the languages that are enabled in the `languages` array.

**Comment by rwols** [comment]
So if I understand correctly, #37 will take care of probing files when ST starts, but we don't have a solution yet for when the user opens a view.

**Comment by rchl** [comment]
That's not correct. It will handle "probe" in either case.

We are computing the value for the `validate` setting from `workspace/configuration` request so it will handle it in all cases.

The `didOpen` part I was referring to has to do with the fact that in VSCode, eslint registers itself to handle all types of files and it will filter out those that it doesn't care about from `didOpen` hook. We, on the other hand, define a limited set of "syntaxes" we support so for we don't have to filter out any "unwanted" files.
