### ISSUE TITLE
LSP-eslint is missing in the Sublime Text 3 Package Control

### ISSUE THREAD

**Issue by itechnocrat** [sublimelsp/LSP-eslint#5]
I did not find this through the package manager.  
What to do?

**Comment by predragnikolic** [comment]
It is not on package control, yet :)

You can read more about the why it's not on package control yet here:
https://github.com/wbond/package_control_channel/pull/7727#issuecomment-569381673
https://github.com/sublimelsp/LSP/issues/854#issuecomment-576403940

If you really want to give it a try. 
You can clone this repo in the packages folder in sublime text.

**Comment by rchl** [comment]
Now available https://packagecontrol.io/packages/LSP-eslint
