### ISSUE TITLE
LSP-eslint silently not runing at a react project

### ISSUE THREAD

**Issue by zisiszikos** [sublimelsp/LSP-eslint#52]
LSP-eslint seems to be correctly installed and works fine for a node.js project, but it doesn't work for a react project.
Nothing is written at the sublime console and the language server status at sublime status bar is not showing at this project.

I use the 16.4.0 node.js version and the following eslint configuration:
```{
  "parser": "@babel/eslint-parser",
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:jest/recommended",
    "plugin:react-hooks/recommended",
    "plugin:prettier/recommended"
  ],
  "plugins": ["react", "jest"],
  "rules": {
    "no-console": 0,
    "jest/no-done-callback": 0
  },
  "parserOptions": {
    "sourceType": "module"
  },
  "globals": {
    "jsdom": true,
    "Promise": true,
    "shallow": true,
    "mount": true,
    "render": true
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true,
    "jest/globals": true
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}
```
I also use eslint version 7.22.0 at package.json.

Is there something else that might prevent the service from running?

**Comment by rchl** [comment]
Open a file where you'd expect LSP-eslint to run and run `LSP: Troubleshoot Server` from the Command Palette.

You can paste the output here (optionally censor any private information before).

**Comment by rwols** [comment]
What syntax are you using and what is the base scope of that syntax?

**Comment by zisiszikos** [comment]
The problem doesn't seem to has something to do with the selected syntax, because whetever syntax I use -Javascript (Babel), JSX or Javascript- it works fine at the node.js project but it doesn't work at the react project. 

And this is the Troubleshoot output:

# Troubleshooting: LSP-eslint
## Version
 - LSP: 1.15.0
 - Sublime Text: 4126
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
/Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin/node "/Users/_USERNAME_/Library/Caches/Sublime Text/Package Storage/LSP-eslint/16.4.0/language-server/out/eslintServer.js" --stdio
```
 - selector
```
source.js | source.ts | source.jsx | source.tsx | source.js.jsx | source.js.react | source.ts.react | text.html.vue | text.html.basic
```
 - priority_selector
```
source.js | source.ts | source.jsx | source.tsx | source.js.jsx | source.js.react | source.ts.react | text.html.vue | text.html.basic
```
 - init_options
```json
{}
```
 - settings
```json
{
  "codeAction": {
    "disableRuleComment": {
      "enable": true, 
      "location": "separateLine"
    }, 
    "showDocumentation": {
      "enable": true
    }
  }, 
  "codeActionOnSave": {
    "enable": true, 
    "mode": "all"
  }, 
  "format": false, 
  "nodePath": null, 
  "onIgnoredFiles": "off", 
  "options": {}, 
  "packageManager": "npm", 
  "probe": [
    "javascript", 
    "javascriptreact", 
    "typescript", 
    "typescriptreact", 
    "html", 
    "vue", 
    "markdown"
  ], 
  "quiet": false, 
  "rulesCustomizations": [], 
  "run": "onType", 
  "useESLintClass": false, 
  "validate": [
    "javascript", 
    "javascriptreact"
  ]
}
```
 - env
```json
{
  "PATH": "/Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin:/Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin:/Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin:/Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin:/Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin:"
}
```

## Active view
 - File name
```
/Users/_USERNAME_/Projects/_MYPROJECT_/src/settings.js
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/Babel/JavaScript (Babel).sublime-syntax"
}
```
 - base scope
```
source.js
```

## Project / Workspace
 - folders
```json
[
  "/Users/_USERNAME_/Projects/_MYPROJECT_"
]
```
 - is project: False

## LSP configuration

```json
{
  "lsp_code_actions_on_save": {}, 
  "show_diagnostics_count_in_view_status": true, 
  "show_diagnostics_panel_on_save": 0
}
```
## System PATH
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /Applications/VMware Fusion.app/Contents/Public
 - /usr/local/go/bin
 - /usr/local/MacGPG2/bin
 - /Library/Apple/usr/bin
 - /Users/_USERNAME_/.nvm/versions/node/v16.4.0/bin
 - /Applications/Sublime Text.app/Contents/SharedSupport/bin
 - /Users/_USERNAME_/.composer/vendor/bin
 - /Users/_USERNAME_/.local/bin
 - /opt/homebrew/sbin
 - /opt/homebrew/bin

**Comment by rchl** [comment]
If you can reproduce in vscode then you could report it at https://github.com/microsoft/vscode-eslint.

Different node versions should not be an issue as long as eslint server runs in a recent enough version.

You could try enabling more verbose logging (https://lsp.sublimetext.io/troubleshooting/#self-help-instructions) and checking if the LSP-eslint server says something relevant before it shuts itself down.

**Comment by rchl** [comment]
Closing due to no response.
We'll look into it more if you provide the requested information.
