### ISSUE TITLE
Why is the minimum requirement of node version so high? (>14)

### ISSUE THREAD

**Issue by shrikrishnaholla** [sublimelsp/LSP-eslint#53]
# Troubleshooting: LSP-eslint
## Version
 - LSP: 1.16.1
 - Sublime Text: 4121
## Server Test Run
 - exit code: -1
 - output
```
Node.js version requirement failed. Expected minimum: 14.0.0, got 12.20.1.
```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh

```
 - selector
```
source.js | source.ts | source.jsx | source.tsx | source.js.jsx | source.js.react | source.ts.react | text.html.vue | text.html.basic
```
 - priority_selector
```
source.js | source.ts | source.jsx | source.tsx | source.js.jsx | source.js.react | source.ts.react | text.html.vue | text.html.basic
```
 - init_options
```json
{}
```
 - settings
```json
{
  "codeAction": {
    "disableRuleComment": {
      "enable": true, 
      "location": "separateLine"
    }, 
    "showDocumentation": {
      "enable": true
    }
  }, 
  "codeActionOnSave": {
    "enable": true, 
    "mode": "all"
  }, 
  "format": false, 
  "nodePath": null, 
  "onIgnoredFiles": "off", 
  "options": {}, 
  "packageManager": "npm", 
  "probe": [
    "javascript", 
    "javascriptreact", 
    "typescript", 
    "typescriptreact", 
    "html", 
    "vue", 
    "markdown"
  ], 
  "quiet": false, 
  "rulesCustomizations": [], 
  "run": "onType", 
  "useESLintClass": false, 
  "validate": [
    "javascript", 
    "javascriptreact"
  ]
}
```
 - env
```json
{}
```

## Active view
 - File name
```
/path/to/file
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/Babel/JavaScript (Babel).sublime-syntax"
}
```
 - base scope
```
source.js
```

## Project / Workspace
 - folders
```json
[
  "/path/to/folder"
]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - /home/<username>/.nvm/versions/node/v12.20.1/bin
 - /usr/local/sbin
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /home/<username>/.local/bin
 

---
I cannot upgrade to v14 yet, because of dependencies in some of my projects. Hence am not able to use this LSP server, although I'd like to. Is there any particular reason that the minimum required version is so high?

**Comment by rwols** [comment]
> Is there any particular reason that the minimum required version is so high?

Yes. VSCode ships with v14.

**Comment by rwols** [comment]
If the user doesn't have `node` in his/her $PATH, then this package offers to download a modern `node` that is local to ST.

I don't know if there's a way to install a local `node` runtime, and then use that local `node`, while also having a system `node` in the $PATH. @rchl probably  knows more about that.

**Comment by rchl** [comment]
Yes, open `Preferences: LSP Utils Settings` from Command Palette and set `local` runtime per instructions there.

The reason that 14 is required is because the underlaying [eslint server](https://github.com/Microsoft/vscode-eslint) requires Node 14+.
