### ISSUE TITLE
Stopped working on one machine with no apparent error messages

### ISSUE THREAD

**Issue by Slapbox** [sublimelsp/LSP-eslint#60]
**Describe the bug**
LSP no longer recognizes some (but not all) ESLint rules and no longer shows the diagnostic panel upon saving despite these settings:

```js
{
  "log_debug": true,
  "show_view_status": true,
  "lsp_format_on_save": false,
  "show_diagnostics_panel_on_save": 1,
  "show_inlay_hints": true,
  "lsp_code_actions_on_save": {
    "source.fixAll": true,
    "source.fixAll.eslint": true,
  },
}
 ```

**To Reproduce**
Unknown

**Expected behavior**
LSP does not begin to silently fail. I'm not actually sure how many days this issue has occurred before I realized

**Screenshots**

**Environment (please complete the following information):**
- OS: Ubuntu 22.04
- Sublime Text version: 4143
- LSP version: 1.21
- Language servers used: ESLint & TypeScript

**Additional context**
Another machine with an identical configuration continues to work and I cannot make it fail there.

**Comment by rchl** [comment]
Your issue seems specific to LSP-eslint so transferred there.

Try to run npx eslint in the root of the root. You will most likely get the same error which would indicate that there is an issue with your eslint configuration or dependencies.

If it works on the command line then please provide output of `LSP: Troubleshoot server`

**Comment by Slapbox** [comment]
@rchl thanks for your help. In this case it turned out that `no-use-before-define` was not configured to error, and rather was "off" - I apologize for the wasted time, but thank you for helping me find the underlying issue.
