### ISSUE TITLE
LSP ESLint stops working randomly

### ISSUE THREAD

**Issue by aashish108** [sublimelsp/LSP-eslint#69]
It stops working randomly and thus will not detect simple things, like, this variable has not been defined. This gives a false sense of security that all is ok with my work.

I have to close Sublime Text and open again and then it works.

This is the config when it works, not sure if this will help? 

I initially assumed its cos I put my MacBook Pro to sleep and resume and that causes issues. But even with a fresh load, it seems to stop working at some point but I do not know when.

# Troubleshooting: LSP-eslint
## Version
 - LSP: 2.0.0
 - Sublime Text: 4169
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}",
  "${server_path}",
  "--stdio"
]
```
 - shell command
```sh
"/Users/aashishsharma/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/18.18.1/node/bin/node" "/Users/aashishsharma/Library/Caches/Sublime Text/Package Storage/LSP-eslint/18.18.1/language-server/out/eslintServer.js" --stdio
```
 - selector
```
source.js | source.ts | source.jsx | source.tsx | source.js.jsx | source.js.react | source.ts.react | text.html.vue | text.html.basic
```
 - priority_selector
```
source.js | source.ts | source.jsx | source.tsx | source.js.jsx | source.js.react | source.ts.react | text.html.vue | text.html.basic
```
 - init_options
```json
{}
```
 - settings
```json
{
  "codeAction": {
    "disableRuleComment": {
      "commentStyle": "line",
      "enable": true,
      "location": "separateLine"
    },
    "showDocumentation": {
      "enable": true
    }
  },
  "codeActionOnSave": {
    "enable": true,
    "mode": "all"
  },
  "experimental": {
    "useFlatConfig": false
  },
  "format": false,
  "ignoreUntitled": false,
  "nodePath": null,
  "onIgnoredFiles": "off",
  "options": {},
  "packageManager": "npm",
  "probe": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue",
    "markdown"
  ],
  "problems": {
    "shortenToSingleLine": false
  },
  "quiet": false,
  "rulesCustomizations": [],
  "run": "onType",
  "useESLintClass": false,
  "validate": [
    "javascript",
    "javascriptreact"
  ]
}
```
 - env
```json
{
  "PATH": "/Users/aashishsharma/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/18.18.1/node/bin:/Users/aashishsharma/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/18.18.1/node/bin:"
}
```

## Active view
 - File name
```
/Users/aashishsharma/Projects/Web/cbs-residential-web/shells/direct-shell/src/components/Shell/Sidebar/components/IntelligentRecommendations/RecommendationContent.js
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc",
  "lsp_active": true,
  "syntax": "Packages/JavaScript/JSX.sublime-syntax"
}
```
 - base scope
```
source.jsx
```

## Project / Workspace
 - folders
```json
[
  "/Users/aashishsharma/Projects/Web/cbs-residential-web"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "/Users/aashishsharma/Projects/Web/cbs-residential-web"
    }
  ]
}
```

## LSP configuration

```json
{
  "diagnostics_panel_include_severity_level": 1,
  "log_debug": false,
  "lsp_code_actions_on_save": {
    "source.fixAll": true,
    "source.organizeImports": false
  },
  "lsp_format_on_save": false,
  "show_diagnostics_count_in_view_status": true,
  "show_diagnostics_panel_on_save": 1,
  "show_diagnostics_severity_level": 4,
  "show_references_in_quick_panel": false
}
```
## System PATH
 - /Applications/Sublime Text.app/Contents/SharedSupport/bin
 - /opt/homebrew/bin
 - /opt/homebrew/sbin
 - /usr/local/bin
 - /System/Cryptexes/App/usr/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
 - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
 - /usr/local/laps

**Comment by predragnikolic** [comment]
Cannot reproduce.

Can you create a sample project that can reproduce the issue? 
That would allow someone to look into it more deeply.

**Comment by predragnikolic** [comment]
I was a bit late.

Feel free to reopen this ticket, 
but please make sure to provide an example that can reproduce the issue.
