### ISSUE TITLE
ESLint Config With `parserOptions.project` Reads From Wrong Directory

### ISSUE THREAD

**Issue by JaceHensley** [sublimelsp/LSP-eslint#70]
I have a mono repo and each package has their own `.eslintrc.js` file with a `parseOptions.project` set to a relative path. I get an error saying that the project cann't be read because no file exists at that path. But it's starting the path at the root of the monorepo rather than relative to the `.eslintrc.js`. I have this `"workingDirectories": [{ "mode": "auto" }]` set for my LSP-eslint setting.

This setup works with VSCode's eslint package with the same `workingDirectories` setting.

I'd be happy to dig into this more or provide more details, just lmk what's needed.

My monorepo is setup like this:

```
package
  package.json
  packages
    /package-1
      .eslintrc.js
      tsconfig.eslint.json
    /package-2
      .eslintrc.js
      tsconfig.eslint.json
```

And the eslint file looks like this:

```js
module.exports = {
  extends: [/* base config package */],
  parserOptions: {
    project: './tsconfig.eslint.json',
  },
}
```

And I get an error saying `"Parsing error: Cannot read file '/path/to/repo/package/tsconfig.eslint.json'. eslint"`

**Comment by rchl** [comment]
The behavior of LSP-eslint should be equivalent to what you see in VSCode. Unless we are maybe using slightly outdated version of the underlaying LSP server and we need to update it.

Do you have a project that could be used to test this issue?

**Comment by JaceHensley** [comment]
For sure, here's a sample project that has auto fixes in VS Code but the error mentioned above in Sublime

https://github.com/JaceHensley/eslint-test

after checking out the repo just a `yarn` at the root is needed

![image](https://github.com/sublimelsp/LSP-eslint/assets/6597117/81bdcc97-f40b-4774-bb7e-676179fe9e68)
![image](https://github.com/sublimelsp/LSP-eslint/assets/6597117/699842f6-09ec-46d7-ac7d-69c4c9c043c0)

Thanks for the response!

**Comment by predragnikolic** [comment]
Hello @JaceHensley.

I tried your example https://github.com/JaceHensley/eslint-test. The good thing is that it works on my side.

My LSP-eslint.sublime-settings file looks like:
```jsonc
// Settings in here override those in "LSP-eslint/LSP-eslint.sublime-settings"

{
    "settings": {
        "workingDirectories": [
            {
                "mode": "auto"
            }
        ]
    }
}

```

<img width="950" alt="Screenshot 2024-06-24 at 19 52 15" src="https://github.com/sublimelsp/LSP-eslint/assets/22029477/a2ff9e61-4d54-4989-97a9-cb1a6e34ba61">

Without the `workingDirectories` setting, I will get the `"Parsing error: Cannot read file '/path/to/repo/package/tsconfig.eslint.json'. eslint"`, so my guess is that you just put the setting in the wrong place.

Fell free to reopen this if you still have any issues.

**Comment by tbremer** [comment]
Had this same issue and your settings resolved it for me, thank you!

**Comment by JaceHensley** [comment]
Ahhh I didn't have it nested in a `"settings"`, thank you for rubber ducking with me!
